# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'MessageDisplayKitDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MessageDisplayKitDemo
pod 'UIImage-Categories', '~> 1.0.0'
pod 'LKbadgeView', '~> 1.1.0'
pod 'SECoreTextView', '~> 0.8.5'
pod 'YYKit', '~> 1.0.7'
end
